"""Change json to db.text

Revision ID: 591e60926cbf
Revises: 
Create Date: 2025-09-16 21:49:22.781458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '591e60926cbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.alter_column('installed_on_servers',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.alter_column('installed_on_servers',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
